"""Adiciona tabela de contratos

Revision ID: 7126d8a6c5e1
Revises: 20e99ef8d056
Create Date: 2025-08-12 11:29:57.608476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7126d8a6c5e1'
down_revision = '20e99ef8d056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('assinatura_secretaria_tipo', sa.String(length=20), nullable=True),
    sa.Column('assinatura_secretaria_dados', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    # ### end Alembic commands ###
