"""Altera cardapio para formato mensal

Revision ID: 733c0a0b9544
Revises: dcb2432b3035
Create Date: 2025-08-19 14:35:50.807960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733c0a0b9544'
down_revision = 'dcb2432b3035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_escola_mes_ano_uc', ['escola_id', 'mes', 'ano'])
        batch_op.drop_column('semana_de')

    with op.batch_alter_table('prato_diario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_prato', sa.Date(), nullable=False))
        batch_op.drop_column('dia_semana')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prato_diario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_semana', sa.INTEGER(), nullable=False))
        batch_op.drop_column('data_prato')

    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semana_de', sa.DATE(), nullable=False))
        batch_op.drop_constraint('_escola_mes_ano_uc', type_='unique')
        batch_op.drop_column('ano')
        batch_op.drop_column('mes')

    # ### end Alembic commands ###
