"""Adiciona modelos para o sistema de protocolo

Revision ID: 3a1c02dc9e45
Revises: af32edc9e0ab
Create Date: 2025-08-12 08:42:01.782508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1c02dc9e45'
down_revision = 'af32edc9e0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_protocolo', sa.String(length=20), nullable=False),
    sa.Column('assunto', sa.String(length=300), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('interessado', sa.String(length=200), nullable=False),
    sa.Column('setor_origem', sa.String(length=150), nullable=False),
    sa.Column('setor_atual', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_protocolo')
    )
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tramitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('setor_origem', sa.String(length=150), nullable=False),
    sa.Column('setor_destino', sa.String(length=150), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('despacho', sa.Text(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tramitacao')
    op.drop_table('anexo')
    op.drop_table('protocolo')
    # ### end Alembic commands ###
