"""Adiciona campos de coordenadas as rotas

Revision ID: af32edc9e0ab
Revises: 900a0f685182
Create Date: 2025-08-11 18:24:58.432539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af32edc9e0ab'
down_revision = '900a0f685182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rota_transporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordenadas_manha', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_tarde', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rota_transporte', schema=None) as batch_op:
        batch_op.drop_column('coordenadas_tarde')
        batch_op.drop_column('coordenadas_manha')

    # ### end Alembic commands ###
