"""Adiciona módulo de merenda escolar

Revision ID: dcb2432b3035
Revises: 386cd7e763c4
Create Date: 2025-08-19 12:19:19.618976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb2432b3035'
down_revision = '386cd7e763c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_merenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estoque_atual', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('diretor_cpf', sa.String(length=14), nullable=True),
    sa.Column('responsavel_merenda_cpf', sa.String(length=14), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['diretor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['responsavel_merenda_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('semana_de', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_merenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('solicitante_cpf', sa.String(length=14), nullable=False),
    sa.Column('autorizador_cpf', sa.String(length=14), nullable=True),
    sa.Column('entregador_cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['autorizador_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['entregador_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['solicitante_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_movimento', sa.DateTime(), nullable=True),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_merenda.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao_merenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.Column('descricao_mudanca', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prato_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('nome_prato', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_merenda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_merenda.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_merenda_id'], ['solicitacao_merenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_item')
    op.drop_table('prato_diario')
    op.drop_table('historico_cardapio')
    op.drop_table('estoque_movimento')
    op.drop_table('solicitacao_merenda')
    op.drop_table('cardapio')
    op.drop_table('escola')
    op.drop_table('produto_merenda')
    # ### end Alembic commands ###
