"""Adiciona módulo de patrimônio

Revision ID: 386cd7e763c4
Revises: f9e510fbc29e
Create Date: 2025-08-19 09:50:14.126638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386cd7e763c4'
down_revision = 'f9e510fbc29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_patrimonio', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('servidor_responsavel_cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['servidor_responsavel_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_patrimonio')
    )
    op.create_table('movimentacao_patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_id', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.Column('local_origem', sa.String(length=200), nullable=False),
    sa.Column('responsavel_anterior_cpf', sa.String(length=14), nullable=True),
    sa.Column('local_destino', sa.String(length=200), nullable=False),
    sa.Column('responsavel_novo_cpf', sa.String(length=14), nullable=True),
    sa.Column('usuario_registro', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['patrimonio_id'], ['patrimonio.id'], ),
    sa.ForeignKeyConstraint(['responsavel_anterior_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['responsavel_novo_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao_patrimonio')
    op.drop_table('patrimonio')
    # ### end Alembic commands ###
