"""Versao Unica e Correta dos Modelos

Revision ID: 5495d3cca9f2
Revises: 
Create Date: 2025-08-09 17:32:29.445660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5495d3cca9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('renewal_key')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servidor',
    sa.Column('num_contrato', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pis_pasep', sa.String(length=20), nullable=True),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('local_trabalho', sa.String(length=150), nullable=True),
    sa.Column('classe_nivel', sa.String(length=50), nullable=True),
    sa.Column('num_contra_cheque', sa.String(length=50), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('lotacao', sa.String(length=100), nullable=True),
    sa.Column('carga_horaria', sa.String(length=50), nullable=True),
    sa.Column('remuneracao', sa.Float(), nullable=True),
    sa.Column('dados_bancarios', sa.String(length=200), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_filename', sa.String(length=100), nullable=True),
    sa.Column('num_contrato_gerado', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('num_contrato'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('num_contrato_gerado')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('veiculo',
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('orgao', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('placa')
    )
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('tipo_combustivel', sa.String(length=50), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('valor_litro', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('servidor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=150), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('oficina', sa.String(length=150), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requerimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autoridade_dirigida', sa.String(length=200), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('natureza', sa.String(length=100), nullable=False),
    sa.Column('natureza_outro', sa.String(length=255), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_inicio_requerimento', sa.Date(), nullable=False),
    sa.Column('duracao', sa.String(length=50), nullable=True),
    sa.Column('periodo_aquisitivo', sa.String(length=20), nullable=True),
    sa.Column('data_retorno_trabalho', sa.Date(), nullable=True),
    sa.Column('informacoes_complementares', sa.Text(), nullable=True),
    sa.Column('parecer_juridico', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requerimento')
    op.drop_table('ponto')
    op.drop_table('nota')
    op.drop_table('manutencao')
    op.drop_table('documento')
    op.drop_table('abastecimento')
    op.drop_table('veiculo')
    op.drop_table('user')
    op.drop_table('servidor')
    op.drop_table('log')
    op.drop_table('license')
    # ### end Alembic commands ###
