"""Adiciona data_conclusao ao Requerimento

Revision ID: d26364464254
Revises: 5495d3cca9f2
Create Date: 2025-08-11 11:06:29.529725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26364464254'
down_revision = '5495d3cca9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requerimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_conclusao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requerimento', schema=None) as batch_op:
        batch_op.drop_column('data_conclusao')

    # ### end Alembic commands ###
