"""Adiciona campos ano_estudo e turno ao aluno

Revision ID: f9e510fbc29e
Revises: 7126d8a6c5e1
Create Date: 2025-08-13 13:03:04.505157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e510fbc29e'
down_revision = '7126d8a6c5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno_transporte', schema=None) as batch_op:
        # Adiciona a coluna com um valor padrão para as linhas existentes
        batch_op.add_column(sa.Column('ano_estudo', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('turno', sa.String(length=20), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno_transporte', schema=None) as batch_op:
        batch_op.drop_column('turno')
        batch_op.drop_column('ano_estudo')

    # ### end Alembic commands ###
