"""Estrutura detalhada para tabela GAM

Revision ID: 66d5a1e8f27b
Revises: 983eb5343332
Create Date: 2025-09-11 15:28:16.188615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d5a1e8f27b'
down_revision = '983eb5343332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_inicial_observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medico_laudo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('dias_afastamento_laudo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('justificativa_laudo', sa.Text(), nullable=True))
        batch_op.alter_column('cid10',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('recomendacoes_medico')
        batch_op.drop_column('observacoes_chefia')
        batch_op.drop_column('data_atendimento')
        batch_op.drop_column('dias_afastamento')
        batch_op.drop_column('justificativa_medica')
        batch_op.drop_column('nome_medico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_medico', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('justificativa_medica', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dias_afastamento', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('data_atendimento', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_chefia', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('recomendacoes_medico', sa.TEXT(), nullable=True))
        batch_op.alter_column('cid10',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('justificativa_laudo')
        batch_op.drop_column('dias_afastamento_laudo')
        batch_op.drop_column('medico_laudo')
        batch_op.drop_column('texto_inicial_observacoes')

    # ### end Alembic commands ###
