"""Adiciona campos detalhados na tabela GAM

Revision ID: 983eb5343332
Revises: f046fec931e3
Create Date: 2025-09-11 15:18:52.287693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983eb5343332'
down_revision = 'f046fec931e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_afastamento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_laudo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nome_medico', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('justificativa_medica', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gam', schema=None) as batch_op:
        batch_op.drop_column('justificativa_medica')
        batch_op.drop_column('nome_medico')
        batch_op.drop_column('data_laudo')
        batch_op.drop_column('dias_afastamento')

    # ### end Alembic commands ###
