"""Criação inicial do banco de dados

Revision ID: 9f5d7af4cabe
Revises: 
Create Date: 2025-09-10 16:31:28.869283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5d7af4cabe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('renewal_key')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('secretaria', sa.String(length=150), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cnh_numero', sa.String(length=20), nullable=True),
    sa.Column('cnh_categoria', sa.String(length=5), nullable=True),
    sa.Column('cnh_validade', sa.Date(), nullable=True),
    sa.Column('rota_descricao', sa.String(length=300), nullable=True),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('veiculo_modelo', sa.String(length=100), nullable=True),
    sa.Column('veiculo_ano', sa.Integer(), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('produto_merenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estoque_atual', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_protocolo', sa.String(length=20), nullable=False),
    sa.Column('assunto', sa.String(length=300), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('interessado', sa.String(length=200), nullable=False),
    sa.Column('setor_origem', sa.String(length=150), nullable=False),
    sa.Column('setor_atual', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_protocolo')
    )
    op.create_table('servidor',
    sa.Column('num_contrato', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pis_pasep', sa.String(length=20), nullable=True),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('local_trabalho', sa.String(length=150), nullable=True),
    sa.Column('classe_nivel', sa.String(length=50), nullable=True),
    sa.Column('num_contra_cheque', sa.String(length=50), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('lotacao', sa.String(length=100), nullable=True),
    sa.Column('carga_horaria', sa.String(length=50), nullable=True),
    sa.Column('remuneracao', sa.Float(), nullable=True),
    sa.Column('dados_bancarios', sa.String(length=200), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_filename', sa.String(length=100), nullable=True),
    sa.Column('num_contrato_gerado', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('num_contrato'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('num_contrato_gerado')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('veiculo',
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('orgao', sa.String(length=150), nullable=True),
    sa.Column('autorizacao_detran', sa.String(length=50), nullable=True),
    sa.Column('validade_autorizacao', sa.Date(), nullable=True),
    sa.Column('renavam', sa.String(length=50), nullable=True),
    sa.Column('certificado_tacografo', sa.String(length=50), nullable=True),
    sa.Column('data_emissao_tacografo', sa.Date(), nullable=True),
    sa.Column('validade_tacografo', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('placa')
    )
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('tipo_combustivel', sa.String(length=50), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('valor_litro', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('assinatura_secretaria_tipo', sa.String(length=20), nullable=True),
    sa.Column('assinatura_secretaria_dados', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('servidor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('diretor_cpf', sa.String(length=14), nullable=True),
    sa.Column('responsavel_merenda_cpf', sa.String(length=14), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['diretor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['responsavel_merenda_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=150), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('oficina', sa.String(length=150), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_patrimonio', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('servidor_responsavel_cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['servidor_responsavel_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_patrimonio')
    )
    op.create_table('requerimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autoridade_dirigida', sa.String(length=200), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('natureza', sa.String(length=100), nullable=False),
    sa.Column('natureza_outro', sa.String(length=255), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_inicio_requerimento', sa.Date(), nullable=False),
    sa.Column('duracao', sa.String(length=50), nullable=True),
    sa.Column('periodo_aquisitivo', sa.String(length=20), nullable=True),
    sa.Column('data_retorno_trabalho', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('informacoes_complementares', sa.Text(), nullable=True),
    sa.Column('parecer_juridico', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rota_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_cpf', sa.String(length=14), nullable=False),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.Column('monitor_cpf', sa.String(length=14), nullable=True),
    sa.Column('escolas_manha', sa.String(length=500), nullable=True),
    sa.Column('itinerario_manha', sa.Text(), nullable=True),
    sa.Column('qtd_alunos_manha', sa.Integer(), nullable=True),
    sa.Column('coordenadas_manha', sa.Text(), nullable=True),
    sa.Column('escolas_tarde', sa.String(length=500), nullable=True),
    sa.Column('itinerario_tarde', sa.Text(), nullable=True),
    sa.Column('qtd_alunos_tarde', sa.Integer(), nullable=True),
    sa.Column('coordenadas_tarde', sa.Text(), nullable=True),
    sa.Column('horario_saida_manha', sa.Time(), nullable=True),
    sa.Column('horario_volta_manha', sa.Time(), nullable=True),
    sa.Column('horario_saida_tarde', sa.Time(), nullable=True),
    sa.Column('horario_volta_tarde', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['motorista_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tramitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('setor_origem', sa.String(length=150), nullable=False),
    sa.Column('setor_destino', sa.String(length=150), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('despacho', sa.Text(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('ano_estudo', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('escola', sa.String(length=200), nullable=False),
    sa.Column('zona', sa.String(length=20), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=200), nullable=False),
    sa.Column('telefone_responsavel', sa.String(length=20), nullable=False),
    sa.Column('endereco_aluno', sa.String(length=300), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('nivel_ensino', sa.String(length=100), nullable=True),
    sa.Column('possui_deficiencia', sa.Boolean(), nullable=True),
    sa.Column('tipo_deficiencia', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['rota_id'], ['rota_transporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'mes', 'ano', name='_escola_mes_ano_uc')
    )
    op.create_table('movimentacao_patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_id', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.Column('local_origem', sa.String(length=200), nullable=False),
    sa.Column('responsavel_anterior_cpf', sa.String(length=14), nullable=True),
    sa.Column('local_destino', sa.String(length=200), nullable=False),
    sa.Column('responsavel_novo_cpf', sa.String(length=14), nullable=True),
    sa.Column('usuario_registro', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['patrimonio_id'], ['patrimonio.id'], ),
    sa.ForeignKeyConstraint(['responsavel_anterior_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['responsavel_novo_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('foto_filename', sa.String(length=100), nullable=True),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_merenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('solicitante_cpf', sa.String(length=14), nullable=False),
    sa.Column('autorizador_cpf', sa.String(length=14), nullable=True),
    sa.Column('entregador_cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['autorizador_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['entregador_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['solicitante_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trecho_rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('tipo_viagem', sa.String(length=10), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['rota_id'], ['rota_transporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_movimento', sa.DateTime(), nullable=True),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_merenda.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao_merenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.Column('descricao_mudanca', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prato_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('data_prato', sa.Date(), nullable=False),
    sa.Column('nome_prato', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_merenda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_merenda.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_merenda_id'], ['solicitacao_merenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_item')
    op.drop_table('prato_diario')
    op.drop_table('historico_cardapio')
    op.drop_table('estoque_movimento')
    op.drop_table('trecho_rota')
    op.drop_table('solicitacao_merenda')
    op.drop_table('ponto')
    op.drop_table('movimentacao_patrimonio')
    op.drop_table('cardapio')
    op.drop_table('aluno_transporte')
    op.drop_table('tramitacao')
    op.drop_table('rota_transporte')
    op.drop_table('requerimento')
    op.drop_table('patrimonio')
    op.drop_table('nota')
    op.drop_table('manutencao')
    op.drop_table('escola')
    op.drop_table('documento_motorista')
    op.drop_table('documento')
    op.drop_table('contrato')
    op.drop_table('anexo')
    op.drop_table('abastecimento')
    op.drop_table('veiculo')
    op.drop_table('user')
    op.drop_table('servidor')
    op.drop_table('protocolo')
    op.drop_table('produto_merenda')
    op.drop_table('motorista')
    op.drop_table('log')
    op.drop_table('license')
    # ### end Alembic commands ###
