"""Adiciona status a tabela GAM

Revision ID: 18d3daa0bb4c
Revises: 66d5a1e8f27b
Create Date: 2025-09-11 15:35:33.209467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d3daa0bb4c'
down_revision = '66d5a1e8f27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Emitida'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gam', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
