"""Cria tabela de Secretarias

Revision ID: 4b63fa75b91f
Revises: 18d3daa0bb4c
Create Date: 2025-09-15 13:12:50.948700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b63fa75b91f'
down_revision = '18d3daa0bb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretaria')
    # ### end Alembic commands ###
