"""Adiciona motivo_cancelamento ao protocolo

Revision ID: 20e99ef8d056
Revises: 3a1c02dc9e45
Create Date: 2025-08-12 09:32:49.803832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e99ef8d056'
down_revision = '3a1c02dc9e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocolo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_cancelamento', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocolo', schema=None) as batch_op:
        batch_op.drop_column('motivo_cancelamento')

    # ### end Alembic commands ###
