"""Adiciona modulo de transporte escolar

Revision ID: 900a0f685182
Revises: d26364464254
Create Date: 2025-08-11 12:13:40.865543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900a0f685182'
down_revision = 'd26364464254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rota_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_cpf', sa.String(length=14), nullable=False),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.Column('monitor_cpf', sa.String(length=14), nullable=True),
    sa.Column('escolas_manha', sa.String(length=500), nullable=True),
    sa.Column('itinerario_manha', sa.Text(), nullable=True),
    sa.Column('qtd_alunos_manha', sa.Integer(), nullable=True),
    sa.Column('escolas_tarde', sa.String(length=500), nullable=True),
    sa.Column('itinerario_tarde', sa.Text(), nullable=True),
    sa.Column('qtd_alunos_tarde', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['motorista_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('escola', sa.String(length=200), nullable=False),
    sa.Column('zona', sa.String(length=20), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=200), nullable=False),
    sa.Column('telefone_responsavel', sa.String(length=20), nullable=False),
    sa.Column('endereco_aluno', sa.String(length=300), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rota_id'], ['rota_transporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_transporte')
    op.drop_table('rota_transporte')
    # ### end Alembic commands ###
