"""Adiciona vinculo de secretaria aos veiculos

Revision ID: a509493719df
Revises: fd014ede3502
Create Date: 2025-09-18 11:25:03.918988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a509493719df'
down_revision = 'fd014ede3502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        # Adiciona a nova coluna 'secretaria_id'
        batch_op.add_column(sa.Column('secretaria_id', sa.Integer(), nullable=False, server_default='1'))

        # ADICIONA UM NOME PARA A RESTRIÇÃO (CONSTRAINT)
        batch_op.create_foreign_key(
            "fk_veiculo_secretaria_id", # Nome da restrição
            'secretaria', ['secretaria_id'], ['id']
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_constraint("fk_veiculo_secretaria_id", type_='foreignkey')
        batch_op.drop_column('secretaria_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
