"""Cria a tabela GAM

Revision ID: f046fec931e3
Revises: 9f5d7af4cabe
Create Date: 2025-09-11 15:11:26.720721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f046fec931e3'
down_revision = '9f5d7af4cabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_num_contrato', sa.String(length=50), nullable=False),
    sa.Column('observacoes_chefia', sa.Text(), nullable=False),
    sa.Column('cid10', sa.String(length=10), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(), nullable=True),
    sa.Column('recomendacoes_medico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_num_contrato'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gam')
    # ### end Alembic commands ###
