"""Vincula usuarios e servidores a secretarias

Revision ID: fd014ede3502
Revises: 4b63fa75b91f
Create Date: 2025-09-15 13:38:57.737820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd014ede3502'
down_revision = '4b63fa75b91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secretaria_id', sa.Integer(), nullable=True))
        # ADICIONA UM NOME PARA A RESTRIÇÃO (CONSTRAINT)
        batch_op.create_foreign_key(
            "fk_servidor_secretaria_id", # Nome da restrição
            'secretaria', ['secretaria_id'], ['id']
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secretaria_id', sa.Integer(), nullable=True))
        # ADICIONA UM NOME PARA A RESTRIÇÃO (CONSTRAINT)
        batch_op.create_foreign_key(
            "fk_user_secretaria_id", # Nome da restrição
            'secretaria', ['secretaria_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('secretaria_id')

    with op.batch_alter_table('servidor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('secretaria_id')

    # ### end Alembic commands ###
